services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
